module.exports = [ { id: '5tUxALySUopW5JtBPbf9Im',
    name: 'Walk In Space',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 1,
    duration: 301013,
    year: 2004 },
  { id: '3kEj1wXrRuFoh15CLJD43E',
    name: 'Reanimo',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 2,
    duration: 292826,
    year: 2004 },
  { id: '18puoFTkOZpR1dWyQ1WDDt',
    name: 'Lava',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 3,
    duration: 272533,
    year: 2004 },
  { id: '0eC0u1xj46wGE9pUPJQWw1',
    name: 'Open a Door',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 4,
    duration: 87066,
    year: 2004 },
  { id: '7oaEQacZcvkQ1VUxQHHb8W',
    name: 'Themes from the Big Red',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 5,
    duration: 318253,
    year: 2004 },
  { id: '4LgJeHub6znZ45ilERmQdb',
    name: 'Bolus',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 6,
    duration: 282306,
    year: 2004 },
  { id: '5omUMeIjItGPoP6RlrywaD',
    name: 'Rock The Whole Planet',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 7,
    duration: 219720,
    year: 2004 },
  { id: '5B40pjsryRwg6hbUjD7LeC',
    name: 'Big Bang',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 8,
    duration: 281146,
    year: 2004 },
  { id: '1WY0AC588VbJhVs1XDHKLe',
    name: 'Lady Nebula',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 10,
    duration: 224040,
    year: 2004 },
  { id: '6opCzd6IOqPGkdn1Kkas87',
    name: 'Music To Watch Aliens By',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 11,
    duration: 167466,
    year: 2004 },
  { id: '5l6YLTYkiwlnMtK5RQugB7',
    name: 'Cluster Buster',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 9,
    duration: 310533,
    year: 2004 },
  { id: '5eHLxiUSE6oKBuffxZ8J4T',
    name: 'Vicious Delicious',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 3,
    duration: 444906,
    year: 2007 },
  { id: '0JGxnJlUVo0V2lf3waNFkZ',
    name: 'Return to Ert',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 13,
    duration: 467280,
    year: 2004 },
  { id: '3AxOIDbfsIUSsuWfUdkvOs',
    name: 'Artillery',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 2,
    duration: 268120,
    year: 2007 },
  { id: '6r7XGyCsFwYIjodkzKsxwk',
    name: 'Heavyweight',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 4,
    duration: 521013,
    year: 2007 },
  { id: '2MhWOwy6fjN9j5QY290z8d',
    name: 'Suliman',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 5,
    duration: 370760,
    year: 2007 },
  { id: '5ys8KLnm67SSjK3dXTuoDK',
    name: 'Synergy',
    album: 'Fingathing & The Big Red Nebula Band',
    artist: [ 'Fingathing' ],
    number: 12,
    duration: 329706,
    year: 2004 },
  { id: '1hUKa46QHBiif7oDYf2iKN',
    name: 'Special Place',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 7,
    duration: 413466,
    year: 2007 },
  { id: '6bPlGL7ZAts3zu2CiZLm77',
    name: 'In Front Of Me',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 8,
    duration: 268653,
    year: 2007 },
  { id: '1Nukcy7xk7AbS7MtkaiOe3',
    name: 'Becoming Insane',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 1,
    duration: 440266,
    year: 2007 },
  { id: '3SvYVSC7o3Ee3QLLHO6QY9',
    name: 'Eat It Raw',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 9,
    duration: 390600,
    year: 2007 },
  { id: '3YzeozjVpmh81J5Mc6gNG9',
    name: 'Forgive Me',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 6,
    duration: 209440,
    year: 2007 },
  { id: '3YKR7Wglf9JvWg5O7xdA5g',
    name: 'We Got It For Cheap (Intro) - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 1,
    duration: 221893,
    year: 2006 },
  { id: '40RYtDQwVLnfH4WzhxEqOQ',
    name: 'Ride Around Shining - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse', 'Ab Liva' ],
    number: 5,
    duration: 236226,
    year: 2006 },
  { id: '6klcfLeLG0gv64vGjs05FL',
    name: 'Momma I\'m So Sorry - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 2,
    duration: 237413,
    year: 2006 },
  { id: '1IAtShkPcFnvYQPp6Rfv3Q',
    name: 'Change The Formality',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 10,
    duration: 464026,
    year: 2007 },
  { id: '6cAldqwmbUwpM8D17FWtPL',
    name: 'Mr. Me Too',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 3,
    duration: 221906,
    year: 2006 },
  { id: '4sSbU5gOeamGxMSi9N14OE',
    name: 'Before',
    album: 'Vicious Delicious',
    artist: [ 'Infected Mushroom' ],
    number: 11,
    duration: 417066,
    year: 2007 },
  { id: '5yQrDTZQWPbhbpGW7acvmm',
    name: 'Hello New World - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 7,
    duration: 252106,
    year: 2006 },
  { id: '2F38A3ce3ORI7tyi8IPdku',
    name: 'Chinese New Year - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 11,
    duration: 234600,
    year: 2006 },
  { id: '50Z0VBnnFU4h2xZkod0m7e',
    name: 'Wamp Wamp (What It Do) - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse', 'Slim Thug' ],
    number: 4,
    duration: 240253,
    year: 2006 },
  { id: '7BG8ObGd0U2C6zsGQK9Qju',
    name: 'Oasiz (Oriental Chill Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'The Man Behind C.' ],
    number: 1,
    duration: 363763,
    year: 2009 },
  { id: '3yAm2Q4FA2Tb8iGORHPvFA',
    name: 'Trill - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 10,
    duration: 283986,
    year: 2006 },
  { id: '05eHuxWbt05SkgTq2QvJWN',
    name: 'Dirty Money - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 6,
    duration: 226506,
    year: 2006 },
  { id: '37HUD7Mr1zOIDW1QuOgaZH',
    name: 'Nightmares - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse', 'Bilal', 'Pharrell Williams' ],
    number: 12,
    duration: 290280,
    year: 2006 },
  { id: '0MIyU9W5yGG11uMeBdm80J',
    name: 'Keys Open Doors - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse' ],
    number: 8,
    duration: 199426,
    year: 2006 },
  { id: '65N2Czz6g88e28PKHkRgAy',
    name: 'Merry Go Round (Non Beat Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'In Credo' ],
    number: 3,
    duration: 290017,
    year: 2009 },
  { id: '21H0DLy2uHKqXqAYSEfDbV',
    name: 'Saigon Sundown (Asia Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Dragon Lounge' ],
    number: 2,
    duration: 308918,
    year: 2009 },
  { id: '7otdqwAGcxXukASrLKpVD7',
    name: 'Sea of Eden (Vocal Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'In Credo' ],
    number: 7,
    duration: 246828,
    year: 2009 },
  { id: '0yFneYkInwJHqZrif7kMxf',
    name: 'Mahasamadhi (Oriental Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Dragon Lounge' ],
    number: 9,
    duration: 362965,
    year: 2009 },
  { id: '4CPwrpEVR4PJVfq3bQ0X2E',
    name: 'Spiritual Dreams (Mystic Vocal Mix) [feat. Chillwalker]',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Zina Rao', 'Chillwalker' ],
    number: 4,
    duration: 322291,
    year: 2009 },
  { id: '5L7G7MRGENQ7QPo7G1vKFK',
    name: 'Golden Memories (Lo-Fi Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Skyway' ],
    number: 10,
    duration: 412777,
    year: 2009 },
  { id: '6l6W3q7EXzxrlWoHkkxsju',
    name: 'Dubai Nights (A Touch of Oriental Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Cafe Americaine' ],
    number: 14,
    duration: 331588,
    year: 2009 },
  { id: '7fS6emd0HfVz5DZCPBH2VW',
    name: 'Ain\'t Cha - Main Version - Explicit',
    album: 'Hell Hath No Fury',
    artist: [ 'Clipse', 'Re-Up Gang' ],
    number: 9,
    duration: 281773,
    year: 2006 },
  { id: '2tuixiGveTrPCqRHaQ8ope',
    name: 'Around the World (Saxophonic Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Frank Borell' ],
    number: 8,
    duration: 258113,
    year: 2009 },
  { id: '6a4e7B200jrVuEziFXdiNn',
    name: 'Welcome 2 Paradise (Dark Wave)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Sofa Sweeper' ],
    number: 5,
    duration: 365968,
    year: 2009 },
  { id: '7HjBO0sRbRszC2uvPR547r',
    name: 'Kansai Sunset (Osaka Lounge Mix) [feat. Tomoko]',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Jazz Connection', 'Tomoko' ],
    number: 6,
    duration: 341193,
    year: 2009 },
  { id: '6ryk6nY6x5iweMkahnmSLX',
    name: 'Ancient Reflections (Dreamsphere Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Indigo Seven' ],
    number: 11,
    duration: 477468,
    year: 2009 },
  { id: '33PBQ0DgznOXi7LdY7fH3i',
    name: 'Annoying Pictures (Saxy Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Kid Coconutz' ],
    number: 13,
    duration: 386426,
    year: 2009 },
  { id: '6GkKNlXnfoaZwJIt91bkqp',
    name: 'Kamasutra (Full Ambience Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'In Credo' ],
    number: 12,
    duration: 424614,
    year: 2009 },
  { id: '1tMzzGUOtBpFzPnt0BWELm',
    name: 'Electric Emotion (Mystic Steps Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Dreamscape' ],
    number: 16,
    duration: 282806,
    year: 2009 },
  { id: '4ItTn2ymTxK06TVmVFnkVN',
    name: 'Hope with U (Timeless Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'The Man Behind C.' ],
    number: 19,
    duration: 406256,
    year: 2009 },
  { id: '4bkQHGrK4KNNjQxYhnVEzF',
    name: 'Northern Star (Dark Relax Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Thinkingmachine' ],
    number: 17,
    duration: 327911,
    year: 2009 },
  { id: '7CdBe535315JOJtwBB4Yg8',
    name: 'Where Do You (Ambient Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Noise Boyz' ],
    number: 18,
    duration: 355404,
    year: 2009 },
  { id: '6eT3XrDT34c73ccESPx6aw',
    name: 'The Girl (Mystic Eyes Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Noise Boyz' ],
    number: 22,
    duration: 367246,
    year: 2009 },
  { id: '1vR5sJily5nOhfgL7YcFPM',
    name: 'Artico Purcente (Orbit Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Richard van Arp' ],
    number: 21,
    duration: 270883,
    year: 2009 },
  { id: '7BVCWKrc5391rfRmGhyQnI',
    name: 'Freedom (Long Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'In Credo' ],
    number: 27,
    duration: 404120,
    year: 2009 },
  { id: '6vSriYebGp5DYad5IfTgNm',
    name: 'Mandala (Dreamers Lounge Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Mahoroba' ],
    number: 25,
    duration: 430207,
    year: 2009 },
  { id: '0NJGx8UALiYOnE8iUZbs12',
    name: 'New Dawn (Cold Sunset Guitar Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Dessert Tunes' ],
    number: 23,
    duration: 342177,
    year: 2009 },
  { id: '7mb2BWAJJQuCLOY7tAHU1r',
    name: 'Walls of Potala (Meditation Groove Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'The Gentle Spirit' ],
    number: 24,
    duration: 420020,
    year: 2009 },
  { id: '42NPouVLCFrw1bQvq0ejYP',
    name: 'Eastern Memories (Mystic Jazz Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Noise Boyz' ],
    number: 15,
    duration: 273763,
    year: 2009 },
  { id: '5wX77vcK3OnDIs00jJY8h7',
    name: 'Future Patch (Space Chill Version)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Frank Borell' ],
    number: 28,
    duration: 308372,
    year: 2009 },
  { id: '0WCNycfskYOYB2rOy0B6Pt',
    name: 'Take Me 2 the Sea (Floating Voice Mix) [feat. Mirjam]',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Orange Music', 'Mirjam' ],
    number: 20,
    duration: 416332,
    year: 2009 },
  { id: '5Fr0X6uumJezD4VNRM1aiz',
    name: 'Alladdin (Mystic Lounge Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Orange Music' ],
    number: 26,
    duration: 384869,
    year: 2009 },
  { id: '7jwQhXguQuxLtKSp9f3716',
    name: 'Spacelounge 05 (Blue Planet Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Thinkingmachine' ],
    number: 30,
    duration: 252133,
    year: 2009 },
  { id: '1ZojHmVMMGzJacZCk45qdZ',
    name: 'Inanely Brazen (Daydream Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Noise Boyz' ],
    number: 29,
    duration: 266205,
    year: 2009 },
  { id: '6Y2PnvwjESGJw2JOXKmftX',
    name: 'Dreamy Faces (Paris Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Green Lemon' ],
    number: 31,
    duration: 366968,
    year: 2009 },
  { id: '4OxbwsYNw8OmWAm1CSnKkP',
    name: 'High Groove (Oriental Jam Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'The Man Behind C.' ],
    number: 33,
    duration: 340033,
    year: 2009 },
  { id: '7CrUBZuQ4tZaIzv1HWrSgp',
    name: 'Nautica (Weightless Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Dreamscape' ],
    number: 32,
    duration: 380041,
    year: 2009 },
  { id: '53AP7os8hD4eCK8re008z3',
    name: 'The Spacefly (Blue Planet Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Thermodynamics' ],
    number: 34,
    duration: 419131,
    year: 2009 },
  { id: '0BK6eRMmq1U2iLP7mPt9F8',
    name: 'Times (Timeless Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Skyway' ],
    number: 36,
    duration: 414110,
    year: 2009 },
  { id: '66cvR0ZvGfcETVPDdK2RP7',
    name: 'Sonic Overdrive (Electric Horizon Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'The Man Behind C.' ],
    number: 40,
    duration: 387912,
    year: 2009 },
  { id: '2UmWAr9E72WTRr2c9YNqNP',
    name: 'The Mystical Groom (Storyboard Edit) [feat. Bernd Langer]',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Magic Life', 'Bernd Langer' ],
    number: 39,
    duration: 311470,
    year: 2009 },
  { id: '4LVFlfUBAEP19yZD2lYg3H',
    name: 'World in Balance (Spacelounge Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Sleeptalker' ],
    number: 35,
    duration: 304530,
    year: 2009 },
  { id: '5akBBswiPWcpDXxugqTxQC',
    name: 'Path to Shambhala (Mystic Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Indigo Seven' ],
    number: 41,
    duration: 526814,
    year: 2009 },
  { id: '57hy5PYyQ3LCULv2PWCRef',
    name: 'Small Machine (Sad Piano Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Kid Coconutz' ],
    number: 37,
    duration: 335584,
    year: 2009 },
  { id: '2u7GzAof431o86z7SpWTxx',
    name: 'Indian Lounge',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Citrus Jam' ],
    number: 38,
    duration: 316975,
    year: 2009 },
  { id: '7lVVNHF5z9WU8zyrT7JjBu',
    name: 'The Seven Sense (Behind the Horizon Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Dreamscape' ],
    number: 42,
    duration: 311402,
    year: 2009 },
  { id: '7lzCktbYyjkv4CXeUFlP9v',
    name: 'Lolita dezio (dreamreality mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'In Credo' ],
    number: 45,
    duration: 209095,
    year: 2009 },
  { id: '2j5tfPkyQ5jmui93CeplUt',
    name: 'Journey to Eternity (Loungetrip Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Frank Borell' ],
    number: 44,
    duration: 263546,
    year: 2009 },
  { id: '5u3s2ztIW9AGhNc80pW4jm',
    name: 'Cherry Verlando (Full Chill Cut)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Medicin Men' ],
    number: 48,
    duration: 526907,
    year: 2009 },
  { id: '3cduTinSUveDDGftrnaTgo',
    name: 'Leyla (Dreamreality Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Frank Borell' ],
    number: 47,
    duration: 330024,
    year: 2009 },
  { id: '7bW2iBCFn8cKfvCwJ97nze',
    name: 'Ethnic Summer Chill',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Silent Voices' ],
    number: 46,
    duration: 292475,
    year: 2009 },
  { id: '2eY0vKQc30fL4lrKONH8QY',
    name: 'East of Eden\'s Gate (Over the Clouds Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Indigo Seven' ],
    number: 49,
    duration: 499438,
    year: 2009 },
  { id: '4zEn4rJiZfM5wMfYKe1cpV',
    name: 'Breathe Again',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People', 'Rachael Roberts' ],
    number: 6,
    duration: 241106,
    year: 2006 },
  { id: '6QLp8WLQlkqSd9l5fEt36R',
    name: 'Moon',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 2,
    duration: 227866,
    year: 2006 },
  { id: '5x823Kkxfwzs8d6mLgGk6y',
    name: 'Basique',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 1,
    duration: 218133,
    year: 2006 },
  { id: '65SqzAg2q2FhRXmPInT9wh',
    name: 'Storm (Mystic Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'Good Chillaz' ],
    number: 50,
    duration: 307667,
    year: 2009 },
  { id: '3ykW6QCJkD26NIHev6qhht',
    name: 'Above The Clouds',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 5,
    duration: 230106,
    year: 2006 },
  { id: '4ly7vLor2IwOhtvvAoQi1G',
    name: 'Unsaid',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 3,
    duration: 228413,
    year: 2006 },
  { id: '5CFafAQg3agw4NONL48HKi',
    name: 'Intermezzo',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 7,
    duration: 37733,
    year: 2006 },
  { id: '1HucmDkA4vVL7XXzuszR9S',
    name: 'Behind Closed Doors (Edit)',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 12,
    duration: 310013,
    year: 2006 },
  { id: '4IUgpL0CgSiloUOHzgd6Qe',
    name: 'Start Shootin\'',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 13,
    duration: 216666,
    year: 2006 },
  { id: '2T8JelG14VBFUh0iiw4BkJ',
    name: 'Fisticuffs At Dawn',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 11,
    duration: 62120,
    year: 2006 },
  { id: '6JvMs7woqyqvPkwrcd9D52',
    name: 'Last Fare',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 10,
    duration: 165373,
    year: 2006 },
  { id: '6RDwxwHO8gMuULJwpXEN6j',
    name: 'Idiom',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 8,
    duration: 345906,
    year: 2006 },
  { id: '2QTrt6V7daDbIdPuKDPtmB',
    name: 'Queen of Rainforest (Nature Mix)',
    album: 'Buddha Deluxe Lounge - Mystic Chill Sounds',
    artist: [ 'The Gentle Spirit' ],
    number: 43,
    duration: 381172,
    year: 2009 },
  { id: '1n8v1S5WpyZxl7cC6H9wzg',
    name: 'Inutile Et Indispensable',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 9,
    duration: 298133,
    year: 2006 },
  { id: '1bhRkHaQAVKNlH4arrrJQv',
    name: 'Eitheror',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 4,
    duration: 345266,
    year: 2006 },
  { id: '2I7vBFkgjNPBDQgX3Wp5B9',
    name: 'Gravitas',
    album: 'Mickey Mouse Operation',
    artist: [ 'Little People' ],
    number: 14,
    duration: 151000,
    year: 2006 } ]
